name: wardrobe_app
description: "An app to help you manage your wardrobe."
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animations: ^2.0.11
  copy_with_extension: ^6.0.1
  file_picker: ^8.1.4
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  share_plus: ^10.0.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.6.1
  equatable: ^2.0.5
  copy_with_extension_gen: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/type_icons/light_mode/
    - assets/type_icons/dark_mode/
    - assets/logo.png

flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: true
